name: Deploy to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Build application
      run: npm run build

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/deploy_key
        
    - name: Add known hosts
      run: |
        ssh-keyscan -H ec2-44-216-59-69.compute-1.amazonaws.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/deploy_key ubuntu@ec2-44-216-59-69.compute-1.amazonaws.com "echo 'SSH test successful'"
      
    - name: Deploy to AWS
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/deploy_key ubuntu@ec2-44-216-59-69.compute-1.amazonaws.com '
          cd /home/ubuntu/brmh-frontend-v2 && \
          git pull origin main && \
          npm install --legacy-peer-deps && \
          npm run build && \
          
          # Install PM2 globally with sudo
          sudo npm install -g pm2 && \
          
          # Stop any existing instances
          pm2 stop brmh-frontend || true && \
          pm2 delete brmh-frontend || true && \
          
          # Start the application as a system service
          pm2 start npm --name "brmh-frontend" -- start && \
          
          # Save PM2 process list
          pm2 save && \
          
          # Remove any existing startup script
          sudo pm2 unstartup systemd || true && \
          
          # Generate new startup script
          sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu && \
          
          # Reload systemd daemon
          sudo systemctl daemon-reload && \
          
          # Enable and start the PM2 service
          sudo systemctl enable pm2-ubuntu && \
          sudo systemctl start pm2-ubuntu && \
          
          # Verify the service is running
          sudo systemctl status pm2-ubuntu && \
          
          # Check PM2 status
          pm2 status
        ' 