name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    
    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
    
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        cat >>~/.ssh/config <<END
        Host ec2
          HostName ec2-44-216-59-69.compute-1.amazonaws.com
          User ubuntu
          IdentityFile ~/.ssh/deploy_key
          StrictHostKeyChecking no
        END
    
    - name: Deploy to EC2
      run: |
        # Create deployment directory if it doesn't exist
        ssh ec2 'mkdir -p ~/brmh-frontend'
        
        # Copy build files to EC2
        scp -r .next ec2:~/brmh-frontend/
        scp -r public ec2:~/brmh-frontend/
        scp package.json ec2:~/brmh-frontend/
        scp package-lock.json ec2:~/brmh-frontend/
        scp next.config.js ec2:~/brmh-frontend/
        
        # Install dependencies and restart the application on EC2
        ssh ec2 'cd ~/brmh-frontend && npm install --legacy-peer-deps --production && pm2 restart brmh-frontend || pm2 start npm --name "brmh-frontend" -- start' 